# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{feature-rich}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["hallelujah"]
  s.date = %q{2011-03-01}
  s.description = %q{Conditional statement to chose feature in your application }
  s.email = %q{hery@rails-royce.org}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/feature-rich.rb",
    "lib/feature-rich/config.rb",
    "lib/feature-rich/engine.rb",
    "lib/feature-rich/group_feature.rb",
    "lib/feature-rich/model_behaviour.rb",
    "lib/feature-rich/railtie.rb",
    "spec/config_spec.rb",
    "spec/db.yml",
    "spec/db/migrate/001_create_super_heros.rb",
    "spec/db/migrate/002_create_features.rb",
    "spec/db_helper.rb",
    "spec/engine_spec.rb",
    "spec/group_spec.rb",
    "spec/helper.rb",
    "spec/model_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/hallelujah/feature-rich}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{A activerecord based selectionable feature}
  s.test_files = [
    "spec/config_spec.rb",
    "spec/db/migrate/001_create_super_heros.rb",
    "spec/db/migrate/002_create_features.rb",
    "spec/db_helper.rb",
    "spec/engine_spec.rb",
    "spec/group_spec.rb",
    "spec/helper.rb",
    "spec/model_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 2.3.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_runtime_dependency(%q<activerecord>, ["~> 2.3.2"])
    else
      s.add_dependency(%q<activerecord>, ["~> 2.3.2"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_dependency(%q<activerecord>, ["~> 2.3.2"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 2.3.2"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.0.10"])
    s.add_dependency(%q<activerecord>, ["~> 2.3.2"])
  end
end

