require 'rubygems'
gem 'activerecord', '~> 2.3.2'
require 'activerecord'
require 'feature-rich/engine'
require 'feature-rich/config'
require 'feature-rich/model_behaviour'
require 'feature-rich/group_feature'
